# Generated by Django 4.0.4 on 2022-05-14 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersubmittedanswer_delete_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_limit',
        ),
    ]
