# Generated by Django 4.0.4 on 2022-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_skills_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skills',
        ),
        migrations.AddField(
            model_name='skill',
            name='s1',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='s2',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='s3',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='sv1',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='sv2',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='sv3',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
